eureka:
  client:
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/

excludeUrl: /api/upload/uploadFile,/api/chat/chat
filterUrl: /api/manage/,/api/upload/,/api/chat/,/api/workflow/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            ribbon:
              ReadTimeout:1000
              ConnectTimeout:1000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

safeApi: /api/manage/user/captcha,/api/manage/user/login
safeDomain: http://localhost,http://localhost:8888,http://localhost:8880,http://47.100.119.102

server:
  port: 8201
  servlet:
    contextPath: /

spring:
  application:
    name: lxt-gateway
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
zuul:
  add-host-header: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    lxt-chat:
      path: /api/chat/**
      serviceId: lxt-chat
      stripPrefix: true
    lxt-upload:
      path: /api/upload/**
      serviceId: lxt-upload
      stripPrefix: true
    lxt-manage:
      path: /api/manage/**
      serviceId: lxt-manage
      stripPrefix: true
    lxt-workflow:
      path: /api/workflow/**
      serviceId: lxt-workflow
      stripPrefix: true