eureka:
  client:
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: http://localhost:8101/lxt-eureka/eureka/

filterUrl: /api/manage/,/api/upload/,/api/chat/,/api/workflow/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            ribbon:
              ReadTimeout:1000
              ConnectTimeout:1000

unencryptedApi: /lxt-upload/api/upload

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1


safeApi: /api/user/captcha,/api/user/login

safeDomain: http://localhost,http://localhost:8888,http://47.100.119.102

server:
  port: 8201
  servlet:
    contextPath: /

spring:
  application:
    name: lxt-gateway
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java

zuul:
  add-host-header: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    lxt-chat:
      path: /lxt-chat/**
      serviceId: lxt-chat
      stripPrefix: false
    lxt-upload:
      path: /lxt-upload/**
      serviceId: lxt-upload
      stripPrefix: false
    lxt-manage:
      path: /api/manage/**
      serviceId: lxt-manage
      stripPrefix: true
    lxt-workflow:
      path: /api/workflow/**
      serviceId: lxt-workflow
      stripPrefix: true