eureka:
  client:
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: http://localhost:8101/lxt-eureka/eureka/

filterUrl: /lxt-manage/api/,/lxt-upload/api/,/lxt-chat/api/,/lxt-workflow/api/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            ribbon:
              ReadTimeout:1000
              ConnectTimeout:1000

unencryptedApi: /lxt-upload/api/upload

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1


safeApi: /api/user/captcha,/api/user/login

safeDomain: http://localhost,http://localhost:8888,http://47.100.119.102

server:
  port: 8201
  servlet:
    contextPath: /lxt-gateway

spring:
  application:
    name: lxt-gateway
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    lxt-chat:
      path: /lxt-chat/**
      serviceId: lxt-chat
      stripPrefix: false
    lxt-upload:
      path: /lxt-upload/**
      serviceId: lxt-upload
      stripPrefix: false
    lxt-manage:
      path: /lxt-manage/**
      serviceId: lxt-manage
      stripPrefix: false
