eureka:
  client:
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://localhost:8101/lxt-eureka/eureka/
log:
  path: ~/logs
  level: error
mapper:
  mappers: com.lxt.ms.pdf.mapper
  not-empty: false
  identity: MYSQL
mybatis:
  mapper-locations: com/lxt/ms/**/*Mapper.xml
  type-aliases-package: com.lxt.ms.pdf.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
safeApi: /api/user/captcha,/api/user/login
safeDomain: http://localhost,http://localhost:8888,http://47.100.119.102
security:
  oauth2:
    resource:
      filter-order: 3
server:
  port: 8341
  servlet:
    contextPath: /lxt-pdf
spring:
  application:
    name: lxt-pdf
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  resources:
    static-locations: classpath:/templates/,classpath:/static/,classpath:/pdf/