eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/lxt-eureka/eureka/
server:
  port: 8080
  servlet:
    contextPath: /lxt-consumer
spring:
  application:
    name: lxt-consumer
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
  resources: 
    static-locations: classpath:/templates/
  thymeleaf:
    prefix: classpath:/templates/