eureka:
  client:
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: http://localhost:8101/lxt-eureka/eureka/,http://localhost:8102/lxt-eureka/eureka/

server:
  port: 8900
  servlet:
    contextPath: /lxt-config

spring:
  application:
    name: lxt-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ms/lxt-config
          searchPaths: config
          username:
          password: