eureka:
  client:
    registryFetchIntervalSeconds: 300
    serviceUrl:
      defaultZone: http://localhost:8100/lxt-eureka/eureka/

ignoreUrl: /api/upload

safeApi: /api/user/captcha,/api/user/login

safeDomain: http://localhost:8888,http://localhost:8080,http://localhost:8888,http://localhost:8080

server:
  port: 8080
  servlet:
    contextPath: /lxt-gateway

spring:
  application:
    name: lxt-gateway
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
  resources: 
    static-locations: classpath:/templates/
  thymeleaf:
    prefix: classpath:/templates/

zuul:
  routes:
    lxt-manage:
      path: /lxt-manage/**
      serviceId: lxt-manage