server:
  port: 8101
  servlet:
    contextPath: /lxt-eureka
spring:
  application:
    name: lxt-eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8102/lxt-eureka/eureka/