server:
  port: 8801
  servlet:
    contextPath: /lxt-web
spring:
  application:
    name: lxt-web
  devtools:
    restart:
      enable: true
      additional-paths: src/main
  resources: 
    static-locations: classpath:/templates/
  thymeleaf:
    cache: false