eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
      
safeApi: /api/user/captcha,/api/user/login

safeDomain: http://localhost:8888,http://localhost:8080,http://localhost:8888,http://localhost:8080

server:
  port: 8080
  servlet:
    contextPath: /lxt-consumer
    
spring:
  application:
    name: lxt-consumer
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
  resources: 
    static-locations: classpath:/templates/
  thymeleaf:
    prefix: classpath:/templates/