eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8000/eureka/
mapper:
  mappers:  com.lxt.chenjia.dao
  not-empty: false
  identity: MYSQL
mybatis:
  mapper-locations: com/lxt/chenjia/**/*Mapper.xml
  type-aliases-package: com.lxt.chenjia.model
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check      
security:
  allowDomain: http://localhost:8888,http://localhost:8080
server:
  port: 8001  
spring:
  application:
    name: lxt-manage
  datasource:
    url: jdbc:mysql://localhost:3306/lxt_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 1
    maxIdle: 1
    minIdle: 1
    initialSize: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
  resources: 
    static-locations: classpath:/templates/
  thymeleaf:
    prefix: classpath:/templates/