server:
  port: 8000
  servlet:
    contextPath: /
spring:
  application:
    name: lxt-designpattern
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8